import type { Config } from "tailwindcss";
import defaultTheme from "tailwindcss/defaultTheme";
import {createThemes} from "tw-colors";

export default {
  content: ["./app/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Poppins", ...defaultTheme.fontFamily.sans],
      }
    },
  },
  plugins: [
    createThemes({
      light: {
        primary: "#536600",
        "on-primary": "#ffffff",
        "primary-container": "#d2ef6c",
        "on-primary-container": "#171e00",
        secondary: "#5c6146",
        "on-secondary": "#ffffff",
        "secondary-container": "#e0e6c3",
        "on-secondary-container": "#191e08",
        tertiary: "#3a665d",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#bdece1",
        "on-tertiary-container": "#00201b",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#410002",
        background: "#fefcf4",
        "on-background": "#1b1c17",
        surface: "#fefcf4",
        "on-surface": "#1b1c17",
        "surface-variant": "#e3e4d3",
        "on-surface-variant": "#46483c",
        outline: "#77786a",
        divider: "#77786a",
        "inverse-on-surface": "#f3f1e8",
        "inverse-surface": "#30312b",
        "inverse-primary": "#b7d253",
        shadow: "#000000",
        "surface-tint": "#536600",
        "outline-variant": "#c7c8b8",
        "divider-variant": "#c7c8b8",
        scrim: "#000000",
      },
      dark: {
        primary: "#b7d253",
        "on-primary": "#2a3400",
        "primary-container": "#3e4c00",
        "on-primary-container": "#d2ef6c",
        secondary: "#c4caa9",
        "on-secondary": "#2e331b",
        "secondary-container": "#444930",
        "on-secondary-container": "#e0e6c3",
        tertiary: "#a1d0c5",
        "on-tertiary": "#033730",
        "tertiary-container": "#214e46",
        "on-tertiary-container": "#bdece1",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        background: "#1b1c17",
        "on-background": "#e4e3da",
        surface: "#1b1c17",
        "on-surface": "#e4e3da",
        "surface-variant": "#46483c",
        "on-surface-variant": "#c7c8b8",
        outline: "#919283",
        divider: "#919283",
        "inverse-on-surface": "#1b1c17",
        "inverse-surface": "#e4e3da",
        "inverse-primary": "#536600",
        shadow: "#000000",
        "surface-tint": "#b7d253",
        "outline-variant": "#46483c",
        "divider-variant": "#46483c",
        scrim: "#000000",
      },
    }),
  ],
} satisfies Config;
